### PR TITLE
Add extensionAttributes to usercreationrestriction

### PR DESCRIPTION
**Pull request by volkovmqx**
add the ability to restrict user creation with the values/regex of extensionAttributes

### CODE REVIEW

**Comment by volkovmqx** [comment]
@microsoft-github-policy-service agree [company="Increase Your Skills GmbH"]

**Comment by volkovmqx** [comment]
> 

@microsoft-github-policy-service agree [company=" Increase Your Skills GmbH"]

**Comment by volkovmqx** [comment]
@microsoft-github-policy-service agree company="Increase Your Skills GmbH"

**Comment by weilai-irl** [comment]
Hi @volkovmqx 

Thank you for making the PR, and sorry for not getting back to you sooner.

I have reviewed the changes and conducted local tests, they work perfectly. I have created separate PRs for the supported versions of the plugins in #2446, #2447 and #2448, and they will be included in the next release. I'll keep the PR open until the feature makes release.

Thank you again for your quality work.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @volkovmqx 

The requested feature has been included in the releases from today:

- [Release 4.1.4 for Moodle 4.1](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m401).
- [Release 4.2.3 for Moodle 4.2](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m402).
- [Release 4.3.1 for Moodle 4.3](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m403).

Thank you very much for making the feature request. Please give it a try. I'll close the issue for now, but feel free to reopen it if you see any issue.

Regards,
Lai

**Pull request closed without merging**
