### PR TITLE
repository/office365/lang/en/repository_office365.php: lang fix

### PR DESCRIPTION
**Pull request by eugeneventer**
this fixes the moodle phpunit tests ;)

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@eugeneventer__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSOTBOT;

**Comment by eugeneventer** [comment]
```
$ vendor/bin/phpunit --colors core_cache_administration_helper_testcase cache/tests/administration_helper_test.php

Moodle 2.9.4+ (Build: 20160114), pgsql, 4f9acd4bf449ae88ea564bc260fe42c926fb96f8
PHPUnit 3.7.38 by Sebastian Bergmann.

Debugging: String does not exist. Please check your string definition for cachedef_unifiedfolderids/repository_office365
* line 9500 of /lib/moodlelib.php: call to debugging()
* line 614 of /cache/classes/definition.php: call to lang_string->__construct()
* line 804 of /cache/locallib.php: call to cache_definition->get_name()
* line 97 of /cache/tests/administration_helper_test.php: call to cache_administration_helper::get_definition_summaries()
* line ? of unknownfile: call to core_cache_administration_helper_testcase->test_get_summaries()
* line 988 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php: call to ReflectionMethod->invokeArgs()
* line 838 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php: call to PHPUnit_Framework_TestCase->runTest()
* line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit_Framework_TestCase->runBare()
* line 648 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestResult.php: call to advanced_testcase->runBare()
* line 783 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php: call to PHPUnit_Framework_TestResult->run()
* line 779 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php: call to PHPUnit_Framework_TestCase->run()
* line 749 of /vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php: call to PHPUnit_Framework_TestSuite->runTest()
* line 350 of /vendor/phpunit/phpunit/PHPUnit/TextUI/TestRunner.php: call to PHPUnit_Framework_TestSuite->run()
* line 176 of /vendor/phpunit/phpunit/PHPUnit/TextUI/Command.php: call to PHPUnit_TextUI_TestRunner->doRun()
* line 129 of /vendor/phpunit/phpunit/PHPUnit/TextUI/Command.php: call to PHPUnit_TextUI_Command->run()
* line 63 of /vendor/phpunit/phpunit/composer/bin/phpunit: call to PHPUnit_TextUI_Command::main()
E...

Time: 856 ms, Memory: 60.25Mb

There was 1 error:

1) core_cache_administration_helper_testcase::test_get_summaries
Unexpected debugging() call detected.
```

The patch fixes the above phpunit test.

**Comment by jamesmcq** [comment]
Thanks Eugene! I'll include this in our next release.

**Comment by jamesmcq** [comment]
Thanks for the contribution Eugene! 

Your patch is in branches [wip-MSFTMPP-344-m30](https://github.com/Microsoft/o365-moodle/commits/wip-MSFTMPP-344-m30), [wip-MSFTMPP-344-m29](https://github.com/Microsoft/o365-moodle/commits/wip-MSFTMPP-344-m29), [wip-MSFTMPP-344-m28](https://github.com/Microsoft/o365-moodle/commits/wip-MSFTMPP-344-m28), [wip-MSFTMPP-344-m27](https://github.com/Microsoft/o365-moodle/commits/wip-MSFTMPP-344-m27). 

This will be included in our next release.

**Pull request closed without merging**
