### PR TITLE
Allow moodleusers to be renamed when UPN change in Azure AD

### PR DESCRIPTION
**Pull request by PetriAsi**
References:  #1156 
This PR adds sync configuration option and new feature  to rename  usernames in moodle if connected account is renamed in Azure AD.

This will keep moodle users connected to o365 when account name changes and also prevents duplicate account creation.

Users are  matched by comparing Azure Ad objectId and database column objectId in table mdl_local_365_objects.

### CODE REVIEW

**Comment by weilai-irl** [comment]
Hi @PetriAsi,

Thank you for making the PR. This is something that I have always been wanting to work on, but didn't have the availability. I'll merge it locally to test. If everything is working fine, I'll include the changes in the next release.

Could you do me two favours please:

1. Could you squash your commits into one (or two if it makes more sense) please. I'm trying to keep the commit history as clean as possible.
2. Could you specify the assumption / prerequisite on the configuration required for the changes to work please. By briefly reading some commits, I think it requires MS user GUID synced to Moodle user "ID number" profile field, is it the case?

Regards,
Lai

**Comment by PetriAsi** [comment]
After manually changed multiple student accounts in moodle I was motivated to write this :D
I'll cleaned up commits to one. And made one correction more. So pull your local copy.

Regards,
Petri

**Comment by PetriAsi** [comment]
Regarding how it works . 
 No need to use idnumber field.
When iterating over aadusers I collect all object ids in array. Sameway as emails and upns were collected.
 As all linked aad user  objectids exist in mdl_local_o365_objects table, I added query to include all existing moodleusers
that have relation with aadobject id. Exitinguser have now aadid property that contains linked 365 objectid.

Then I could make "multiindex" array ($existingusers) so that all users from moodle is available  with objectid and email.
After that I just do some safety checks that username does not exist moodle before renaming it.

**Comment by PetriAsi** [comment]
@microsoft-github-policy-service agree [company="Satakunnan koulutuskuntayhtymä"]

**Comment by PetriAsi** [comment]
@microsoft-github-policy-service agree company="Satakunnan koulutuskuntayhtymä"

**Comment by PetriAsi** [comment]
@microsoft-github-policy-service agree

**Comment by PetriAsi** [comment]
I have merged this to MOODLE_311_STABLE too (petriasi/feature/renamemoodleusers_311). I couls  make an other pull request after this one is merged if needed.

**Comment by PetriAsi** [comment]
To enable objectId based sync in moodle , you have to use upn as moodle username. Also it make sense to keep "Update moodle users" option enables so email attribute is updated also.
But it does not require any additional setup as objectids are already on local_o365_objects table and user are linked with that information. If there's duplicate emails in system as we had left over from previous releases those have to cleaned up by hand.
Just switch update users and this new option on and you are ready to go.

**Comment by PetriAsi** [comment]
@weilai-irl  I just noticed that this need little more work. So I added WIP prefix until this ready to . 
The issue is that current code does not fix existing auth_oidc_tokens correctly, as tokens are checked before moodleuser is renamed.
Could I just remove related oidc_token when renaming moodle user, or  does will it  cause issues?

**Comment by PetriAsi** [comment]
@weilai-irl  I just added oidc token check to this this PR.  It will remove oidc tokens that does not match updated upn username.
This is ready for merge.

**Comment by PetriAsi** [comment]
Is there still  something that I could  do to get this merged?

**Comment by weilai-irl** [comment]
Hi @PetriAsi,

I started testing the PR in a local environment and the initial results are not as good as I would have expected. It may be caused by different test cases that I used compared to what you used in the development of this. I'll list of test cases below, and you can list yours. As you can imagine, this change may potentially have big impact on Moodle accounts using the integration; I'd prefer having having all test cases tested and passed before including it to the release.

Test case 1, user login without user sync:
 - Setup required:
   1. In user field mapping settings, Moodle email mapped to Azure email, and this is set to update on login and user sync.
 - Steps:
   1. Create a new account in Azure AD.
   2. Initial sign in as the user using auth_oidc. Result: user account created with Azure account UPN as Moodle username.
   3. Change the Azure account UPN.
   4. In a new browser session, sign in as the user using auth_oidc.
     - Expected results:
       a. user login successfully,
       b. Moodle account username updated to match Azure account, (may need to consider if there are duplicates).
       c. Moodle account email address updated to match Azure account.
     - Actual results:
       a. works as expected.
       b. Moodle account username is not updated.
       c. works as expected.

Test case 2, user sync without login:
 - Setup required:
   1. In user field mapping settings, Moodle email mapped to Azure email, and this is set to update on login and user sync.
   2. In user sync settings in local_o365, both "create" and "update" options (the first 2) are checked.
 - Steps:
   1. Create a new account in Azure AD.
   2. Run the user sync task. The task should create new Moodle account for the new Azure account.
   3. Change the Azure account UPN.
   4. Rerun the user sync task.
     - Expected results:
       a. no new Moodle account is created.
       b. the username of the existing Moodle account created in step 2 is updated to match Azure account.
       c. the email address of the existing Moodle account created in step 2 is updated to match Azure account.
       d. the connection record of the user in the mdl_local_o365_objects table is updated to contain the updated Azure account UPN.
     - Actual results:
       a. a new Moodle account is created.
       b. failed due to a.
       c. failed due to a. 
       d. the connection record of the existing user is not changed, however a new record is created for the new user. Both records have the same "objectid", which is essentially the Azure user GUID.

These would be the two most straightforward test cases in relation to Azure user UPN change. Once we can get these two passed, we can look at testing other more complicated test cases, e.g. a mixture of login and sync in different orders, or users with manual matchings (therefore don't have Moodle username matching Azure UPN) etc.

As I explained, please explain the test cases you have covered in case I'm missing anything here.

Regards,
Lai

**Comment by PetriAsi** [comment]
Yes I understand that this kind of change is must be done veru carefully.

Thanks for testing  details, for case 1, 
that's probably something that should be fixed in oidc login flow. I must missed something. we are running delta sync so often that moodle is always updated before user login to moodle.  

Regarding test case 2:
Why you expect that :  no new Moodle account is created.
When : In user sync settings in local_o365, both "create" and "update" options (the first 2) are checked.
Is there existing connected moodle user in this case setup?

**Comment by PetriAsi** [comment]
So we need test matrix that cover all possible use cases:

Moodle users: 
non existing user, existing not connected user and existing connected users
Sync settings:
create , update or both checked

with
sync and user browser login ( before sync)


 I would assume that most of real world setups that need  rename moodleuser feature will use  create and update sync options. In those systems there no need connect existing moodle users, or that need is only when moving from users provision from moodle to azure based provision.
For systems that are using manual moodle users  accounts and  users manually connects with 365 there no need this renaming feature.
Would it make sense to to make  this 'idsync' option available only when sync option 'update users'  is in use? That would make it available only when this feature is useful and need. .

**Comment by weilai-irl** [comment]
Hi @PetriAsi,

Thank you for the update.

Regarding your comments on the two listed test cases:
 1. Since the user sync happens in a scheduled task, and the schedule of which can be customised (or even disabled) by site admin, we can't assume user sync always happens after an Azure user UPN change and before the user tries to login. Therefore it will need to be necessary to make the necessary changes in auth_oidc plugin to ensure it handles situations like this properly.
 2. You are right that both "create" and "update" user sync options are (and need to be) enabled. When this happens, when an Azure user UPN change happens, I think the most logical thing that should happen is for the existing Moodle user matching the previous UPN to be updated to with the new UPN (and other profile fields, e.g. email, if such field mappings are configured). The situation that we should try to avoid here is to have a new Moodle account created, so that the user would lose all previous data such as course enrolments, grades and progress etc. Merging two Moodle accounts can be quite messy.
 
I agree your point in your note at https://github.com/microsoft/o365-moodle/pull/2214#issuecomment-1408094522 that we need to have a test MATRIX for a combination of scenarios. We probably need to put a bit more thoughts in this.

I'll try to find more time for this in the coming weeks and make some progress.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @PetriAsi and everyone else who are interested in this,

I finally found some time to do a bit of work in this one. So basically I created a test matrix which involves all the cases that I can think of, and this is how it looks:

Case ID | The user with the old username has logged in already? (token created) | First action after UPN rename | Has potential duplicate accounts | Excepted Behaviour
-- | -- | -- | -- | --
What does this mean? | Logged in users would have token stored in auth_oidc_token table. Users who haven't logged in, but were synced would only have connection record in local_o365_objects table, but no stored token. | Either Login or User sync task run | This indicates if another Moodle user with the same username as the new Microsoft account UPN already exists in Moodle. |  
1 | Yes | Login | No | 1. Rename the Moodle user.2. auth_oidc_token updated with both new values for both "username" and "oidcusername" fields.3. local_o365_objects user connection record "o365name" field updated to new value.
2 | Yes | User sync | No | 1. Rename the Moodle user.2. local_o365_objects user connection record is updated.3. auth_oidc_token updated.
3 | No | Login | No | 1. Rename the Moodle user.2. local_o365_objects user connection record is updated.3. auth_oidc_token updated.
4 | No | User sync | No | 1. Rename the Moodle user.2. local_o365_objects user connection record is updated.
5 | Yes | Login | Yes | 1. Throw exception and do not rename Moodle user.
6 | Yes | User sync | Yes | 1. Display error message saying rename attempt failed in user sync task run.
7 | No | Login | Yes | 1. Throw exception and do not rename Moodle user.
8 | No | User sync | Yes | 1. Display error message saying rename attempt failed in user sync task run.

Each of the test cases above needs to be tested on the two authentication options (client secret, and certificate) that the plugins support to communicate with Microsoft Graph API too. 

I have created an enhanced solution based on @PetriAsi's work and the changes are in PR #2291 #2292 #2293 for Moodle 4.0 to 4.2. The solution has passed my initial test, and will be tested by our testers. The plan is to include them in the next release.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi all,

I'm happy to announce that this feature is finally included in the release from today. We tested the feature according to the test matrix from my last comment, and all test cases passed.

I'd like to thank @PetriAsi for his contribution in this one.

I'll close this issue for now.

Regards,
Lai

**Pull request closed without merging**
