### PR TITLE
Issue #81: Added support for Microsoft Graph for China

### PR DESCRIPTION
**Pull request by vinhub**
Added support for Microsoft Graph to users using Office 365 for China

### CODE REVIEW

**Comment by jamesmcq** [comment]
Thanks! Patches in wip-MSFTMPP-386-m27, wip-MSFTMPP-386-m28, wip-MSFTMPP-386-m29, wip-MSFTMPP-386-m30

**Comment by juho-jaakkola** [comment]
> Patches in wip-MSFTMPP-386-m27, wip-MSFTMPP-386-m28, wip-MSFTMPP-386-m29, wip-MSFTMPP-386-m30

What does this mean? What is the workflow here?

**Comment by jamesmcq** [comment]
@juho-jaakkola between releases, all code changes are put into "feature branches", which branch from the last release. When a new version is released, all feature branches are merged back into the MOODLE_XX_STABLE branches.

There are four branches, one for each supported Moodle version (Moodle 2.7 - 3.0). "wip-" indicates this is a "work in progress" branch. "MSFTMPP-386" is an internal issue number we use to keep track of work. "-mXX" indicates the Moodle version this branch is for: -m27 for Moodle 2.7, -m28 for Moodle 2.8, etc.

**Comment by juho-jaakkola** [comment]
Apologies for getting off-topic from the issue itself (let me know if you prefer some other medium), but why not simply accept the bugfix to lowest supported branch (currently 2.7) and then merge it up one by one to the higher branches?

After accepting a fix to `MOODLE_27_STABLE` branch:
```
git checkout MOODLE_28_STABLE
git merge MOODLE_27_STABLE

git checkout MOODLE_29_STABLE
git merge MOODLE_28_STABLE

git checkout MOODLE_30_STABLE
git merge MOODLE_29_STABLE

git push --all
```
Now all of your branches have the fix, and there was no need for any other manual work.

**Pull request closed without merging**
