### PR TITLE
Delete users setting fix for M3.8

### PR DESCRIPTION
**Pull request by avegys**

### CODE REVIEW

**Comment by Nab59** [comment]
Hi 
I ve update my plugin with the new version
Now i have that issue after running the task 

Sync users with Azure AD.
Execute scheduled task: Synchroniser des utilisateurs avec Azure AD. (local_o365\task\usersync)
**Cannot obtain task lock**

**Comment by Nab59** [comment]
Hi
The fix doesn t work for me.  Our deleted users in Azur are not deleted in Moodle.

**Comment by nenorojas** [comment]
Hi @Nab59 , 

Can you please provide more details about the error? What's the version of Moodle you are using?

In the related note @avegys explained that users are not deleted from Moodle immediately:

Deleted users who are in the deleted users list in Azure will be suspended. Those users who are permanently deleted from Azure, first of all will be suspended with the first usersync scheduled task run (if they were not yet) and with the next usersync scheduled task run those suspended users will be deleted from Moodle.

Is the other issue related to "Cannot obtain task lock" fully sorted?

Regards

**Comment by Nab59** [comment]
Hi Nenorojas

Our Moodle version is 3.8.2
Actually, the cron task run more than 5 times now and users deleted in Azur are not in Moodle.

About the issue "Cannot obtain task lock" , yes no more exist.

Please help us

**Comment by avegys** [comment]
Hi @Nab59,

Do you have access to your DB? If yes, please check if the users that you expect to be deleted in Moodle has record with objectid in local_o365_objects table. You can search that table by user id.

Best regards,
Andrius

**Pull request closed without merging**
