### PR TITLE
Significant changes to documentation

### PR DESCRIPTION
**Pull request by nimojg-microsoft**
Large edits to several of the documentation files
External Tools for OneNote Class Notebook and Office Mix were merged and renamed
Additional file for Microsoft Block created

### CODE REVIEW

**Comment by nimojg-microsoft** [comment]
Minor changes to Readme.md file only

**Comment by number33** [comment]
@nimojg-microsoft this issue was already integrated internally.  However we can pull it out and add your most recent changes (details here: https://github.com/Microsoft/o365-moodle/pull/156/files/39cf57cb76944c331f874d403ec33d279c18a0fa..f2bdebb328f8e8ebf2603ad2e598166c4402cd43).  I just want to make sure that all of your changes are in for this issue? If not then we can wait till Monday to integrate this issue.  Let me know.

**Comment by number33** [comment]
@nimojg-microsoft  Also the README.md you attached to an email you've sent.  Does this PR contain all of your changes or would you still like the README.md attached to your email to override these changes?

**Comment by nimojg-microsoft** [comment]
I had assumed the other commits (changes to the plugin documentation files) were already cherry picked. The only new bit is the commit about the Readme.md – and you can either take that from this PR (assuming it was in there) or the one I attached.

**Pull request closed without merging**
