### PR TITLE
Improvements based on Office 365 + MS Services review

### PR DESCRIPTION
**Pull request by tlock**
- Implement using lang_string
 - Fix static CSS (auth/oidc//classes/form/adminsetting/iconselect.php)
 - Implement using Moodle curl
 - Fix unit tests for webservices onenoteassignment
 - Fix duplicate indicies
 - Fix auth_oidc user create event type
 - Implement configuration retry limit for filtering.
 - Implement cache for filtering.

### CODE REVIEW

**Comment by number33** [comment]
Hello Tim, I noticed that your pull request adds the following file: ilter/oembed/db/caches_new-138663a97365c4dd6f1c127b341b7b3ec1568049.php.  There are similar files (in content) in Moodle and in the plugins, however they are typically named caches.php, for example:

- admin/tool/uploadcourse/db/caches.php
- repository/office365/db/caches.php
- repository/onenote/db/caches.php
- repository/skydrive/db/caches.php
- mod/glossary/db/caches.php
- availability/condition/grade/db/caches.php
- lib/db/caches.php
- blocks/microsoft/db/caches.php

Can you provide some details as to why the file is named caches_new-138663a97365c4dd6f1c127b341b7b3ec1568049.php?

Also your commit messages sates that you removed duplicate indexes.  Though the names were the same, there are still areas of the code where those indexes would be used.  Below are the files and line numbers (based off of the 2.7 version of the plugins) where those indexes may be used:

- local/o365/classes/feature/calsync/form/subscriptions.php:
   105:         $existingsubsrs = $DB->get_recordset('local_o365_calsub', ['user_id' => $USER->id]);
- local/o365/classes/feature/calsync/observers.php:
   196:         $DB->delete_records('local_o365_calsub', ['user_id' => $userid]);
- local/o365/classes/page/ucp.php:
   123:             $existingsubsrs = $DB->get_recordset('local_o365_calsub', ['user_id' => $USER->id]);
- local/o365/classes/observers.php:
   162:             $DB->delete_records('local_o365_token', ['user_id' => $eventdata['userid']]);
   598:         $DB->delete_records('local_o365_token', ['user_id' => $userid]);
- local/o365/classes/utils.php:
   126:             if ($DB->record_exists('local_o365_token', ['user_id' => $userid])) {
- user/profile/field/o365/field.class.php:
    42:         $o365connected = $DB->record_exists('local_o365_token', ['user_id' => $this->userid]);

Instead those indexes could be renamed.

**Comment by tlock** [comment]
Hi Akin,

I've renamed the cache file in my latest push to the resolve that.

The indexes were removed because user_id is in the other btree index which is used for indexing.

**Comment by tlock** [comment]
Just added this patch:

When German is available, the unit test will fail because the Preferred Language will be set to German.

**Comment by jamesmcq** [comment]
Thanks - this has been reviewed and tested. Patched are in wip-MSFTMPP-472-m27, wip-MSFTMPP-472-m28, wip-MSFTMPP-472-m29, wip-MSFTMPP-472-m30 and will be included in the next release.

**Comment by tlock** [comment]
Hey James,

My 2nd and 3rd patches haven't been applied to wip-MSFTMPP-472* branches yet.

**Comment by jamesmcq** [comment]
Hi Tim - 

Looks like Akin squashed your second commit (the cache filename change) into your first commit, so that's in there. The third commit came in after we created the branches so it looks like it wasn't included as you mentioned, however I believe we resolved the "de" language unit test failed in this commit: https://github.com/Microsoft/o365-moodle/commit/b6c4133c2124ae73ad269c78598e611da1850629 - basically we just used a non-existent language identifier. This test is supposed to test the fall-back to 'en' if the language is not found.

Thanks!
- James

**Pull request closed without merging**
